version: "3.8"
services:
  gym-navigation-redis:
    container_name: gym-navigation-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: zcx5674/gym-navigation-redis
    ports:
      - "6379:6379"
  gym-navigation-database:
    container_name: gym-navigation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: zcx5674/gym-navigation-database
    environment:
      - MARIADB_DATABASE=gym-navigation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
    ports:
      - "3306:3306"